* Authorized Version of the King James Bible 1611
** The Goal
I want to take the text of the Authorized Version (KJV) and turn it into an XML document so that it can be parsed with XML tools. I'm starting with XHTML+RDFa so that it will render in a browser for live preview and because it will be trivial to turn it into an html document, just edit the !DOCTYPE definition at the top. It should be compatible with HTML 5.

** Downloaded the text version from **The Internet Archive**. 
This version is placed in the public domain and the formatting should lend itself to search and replace functions rather than hand editing the entire Bible.

`wget https://archive.org/stream/TheHolyBiblekjv1611Wapocrypha/1611KjvW_apocrypha_djvu.txt`

** Cloned the repository to local drive
cd to the directory where I want the repo to live
`git clone git@github.com:OrthodoxFriar/King_James_Bible.git`

** Twofold Benefits
I am going to be learning and practicing nvim during the process and I'll keep the code here along with comments.

** Macro to add paragraph tags <p>{1:1}content</p>\n{1:2}

** Removing double spaces
%s![^ ]\zs  \+! !g



